name: json_to_form
description: A flutter plugin to use convert Json to Form Basic
version: 0.0.3
author: Victor Alfonso Rodas OÃ±a <victordevcode@gmail.com>
homepage: https://github.com/VictorRancesCode/json_to_form

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


environment:
  sdk: '>=1.20.1 <3.0.0'